import { AdminTier } from '@prisma/client';

/**
 * 권한 목록
 */
export const PERMISSIONS = {
  // 회원 관리
  MEMBERS_VIEW: 'members.view',
  MEMBERS_UPDATE: 'members.update',
  MEMBERS_BAN: 'members.ban',
  MEMBERS_MEMO: 'members.memo',
  MEMBERS_UNMASK_PHONE: 'members.unmask_phone',
  MEMBERS_EXCEL: 'members.excel',
  MEMBERS_TEMP_ACCOUNT: 'members.temp_account',

  // 관리자 관리
  ADMINS_MANAGE: 'admins.manage',
  ADMINS_LOGO: 'admins.logo',
  UNLOCK_ALL: 'unlock.all',

  // 구독 관리
  SUBSCRIPTIONS_MANAGE: 'subscriptions.manage',

  // 채팅 관리
  CHATS_MANAGE: 'chats.manage',

  // 배너/팝업 관리
  BANNERS_MANAGE: 'banners.manage',

  // 고객센터 관리
  SUPPORT_MANAGE: 'support.manage',

  // 감사 로그
  LOGS_VIEW: 'logs.view',

  // 앱 버전 관리
  APP_VERSIONS_MANAGE: 'app_versions.manage',
} as const;

/**
 * 관리자 계층별 기본 권한
 */
export const DEFAULT_PERMISSIONS_BY_TIER: Record<AdminTier, string[]> = {
  INTEGRATED: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_UPDATE,
    PERMISSIONS.MEMBERS_BAN,
    PERMISSIONS.MEMBERS_MEMO,
    PERMISSIONS.MEMBERS_UNMASK_PHONE,
    PERMISSIONS.MEMBERS_EXCEL,
    PERMISSIONS.MEMBERS_TEMP_ACCOUNT,
    PERMISSIONS.ADMINS_MANAGE,
    PERMISSIONS.ADMINS_LOGO,
    PERMISSIONS.UNLOCK_ALL,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.CHATS_MANAGE,
    PERMISSIONS.BANNERS_MANAGE,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.LOGS_VIEW,
    PERMISSIONS.APP_VERSIONS_MANAGE,
  ],
  CEO: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_UPDATE,
    PERMISSIONS.MEMBERS_BAN,
    PERMISSIONS.MEMBERS_MEMO,
    PERMISSIONS.MEMBERS_UNMASK_PHONE,
    PERMISSIONS.MEMBERS_TEMP_ACCOUNT,
    PERMISSIONS.ADMINS_MANAGE,
    PERMISSIONS.SUBSCRIPTIONS_MANAGE,
    PERMISSIONS.CHATS_MANAGE,
    PERMISSIONS.BANNERS_MANAGE,
    PERMISSIONS.SUPPORT_MANAGE,
  ],
  MIDDLE: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_MEMO,
    PERMISSIONS.MEMBERS_TEMP_ACCOUNT,
    PERMISSIONS.CHATS_MANAGE,
    PERMISSIONS.SUPPORT_MANAGE,
  ],
  GENERAL: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.CHATS_MANAGE,
    PERMISSIONS.SUPPORT_MANAGE,
  ],
};
