import { AdminTier } from './enums';

// Permission Keys
export const PERMISSIONS = {
  // 회원 관리
  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_EDIT: 'MEMBER_EDIT',
  MEMBER_DELETE: 'MEMBER_DELETE',
  MEMBER_EXPORT: 'MEMBER_EXPORT',
  MEMBER_MEMO: 'MEMBER_MEMO',

  // 관리자 관리
  ADMIN_VIEW: 'ADMIN_VIEW',
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_EDIT: 'ADMIN_EDIT',
  ADMIN_DELETE: 'ADMIN_DELETE',
  ADMIN_PERMISSION: 'ADMIN_PERMISSION',

  // 채팅 관리
  CHAT_VIEW: 'CHAT_VIEW',
  CHAT_MANAGE: 'CHAT_MANAGE',
  CHAT_DELETE: 'CHAT_DELETE',
  CHAT_KEYWORD_BLOCK: 'CHAT_KEYWORD_BLOCK',

  // 커뮤니티 관리
  COMMUNITY_VIEW: 'COMMUNITY_VIEW',
  COMMUNITY_CREATE: 'COMMUNITY_CREATE',
  COMMUNITY_EDIT: 'COMMUNITY_EDIT',
  COMMUNITY_DELETE: 'COMMUNITY_DELETE',

  // FAQ 관리
  FAQ_VIEW: 'FAQ_VIEW',
  FAQ_CREATE: 'FAQ_CREATE',
  FAQ_EDIT: 'FAQ_EDIT',
  FAQ_DELETE: 'FAQ_DELETE',

  // 신고 관리
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_PROCESS: 'REPORT_PROCESS',

  // 배너 관리
  BANNER_VIEW: 'BANNER_VIEW',
  BANNER_CREATE: 'BANNER_CREATE',
  BANNER_EDIT: 'BANNER_EDIT',
  BANNER_DELETE: 'BANNER_DELETE',

  // 팝업 관리
  POPUP_VIEW: 'POPUP_VIEW',
  POPUP_CREATE: 'POPUP_CREATE',
  POPUP_EDIT: 'POPUP_EDIT',
  POPUP_DELETE: 'POPUP_DELETE',

  // 구독 관리
  SUBSCRIPTION_VIEW: 'SUBSCRIPTION_VIEW',
  SUBSCRIPTION_APPROVE: 'SUBSCRIPTION_APPROVE',
  SUBSCRIPTION_MANAGE: 'SUBSCRIPTION_MANAGE',

  // 할인 이벤트
  DISCOUNT_VIEW: 'DISCOUNT_VIEW',
  DISCOUNT_CREATE: 'DISCOUNT_CREATE',
  DISCOUNT_EDIT: 'DISCOUNT_EDIT',
  DISCOUNT_DELETE: 'DISCOUNT_DELETE',

  // 앱 버전 관리
  APP_VERSION_VIEW: 'APP_VERSION_VIEW',
  APP_VERSION_MANAGE: 'APP_VERSION_MANAGE',

  // 통계
  STATISTICS_VIEW: 'STATISTICS_VIEW',

  // 알림 발송
  NOTIFICATION_SEND: 'NOTIFICATION_SEND',

  // 시스템 설정
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

// Rate Limits
export const RATE_LIMITS = {
  ADMIN_LOGIN_ATTEMPTS: 5,           // 관리자 로그인 시도 횟수
  ADMIN_LOGIN_LOCK_MINUTES: 30,      // 로그인 잠금 시간 (분)
  SMS_PER_DAY: 10,                   // 하루 SMS 발송 제한
  FILE_UPLOAD_MAX_SIZE: 10 * 1024 * 1024, // 10MB
  CHAT_MESSAGE_PER_MINUTE: 60,       // 분당 채팅 메시지 제한
  REPORT_PER_DAY: 10,                // 하루 신고 제한
} as const;

// Default Permissions by Admin Tier
export const DEFAULT_PERMISSIONS: Record<AdminTier, PermissionKey[]> = {
  [AdminTier.INTEGRATED]: Object.values(PERMISSIONS), // 모든 권한

  [AdminTier.CEO]: [
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.MEMBER_DELETE,
    PERMISSIONS.MEMBER_EXPORT,
    PERMISSIONS.MEMBER_MEMO,
    PERMISSIONS.ADMIN_VIEW,
    PERMISSIONS.ADMIN_CREATE,
    PERMISSIONS.ADMIN_EDIT,
    PERMISSIONS.ADMIN_DELETE,
    PERMISSIONS.ADMIN_PERMISSION,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_MANAGE,
    PERMISSIONS.CHAT_DELETE,
    PERMISSIONS.CHAT_KEYWORD_BLOCK,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.COMMUNITY_CREATE,
    PERMISSIONS.COMMUNITY_EDIT,
    PERMISSIONS.COMMUNITY_DELETE,
    PERMISSIONS.FAQ_VIEW,
    PERMISSIONS.FAQ_CREATE,
    PERMISSIONS.FAQ_EDIT,
    PERMISSIONS.FAQ_DELETE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PROCESS,
    PERMISSIONS.BANNER_VIEW,
    PERMISSIONS.BANNER_CREATE,
    PERMISSIONS.BANNER_EDIT,
    PERMISSIONS.BANNER_DELETE,
    PERMISSIONS.POPUP_VIEW,
    PERMISSIONS.POPUP_CREATE,
    PERMISSIONS.POPUP_EDIT,
    PERMISSIONS.POPUP_DELETE,
    PERMISSIONS.SUBSCRIPTION_VIEW,
    PERMISSIONS.SUBSCRIPTION_APPROVE,
    PERMISSIONS.SUBSCRIPTION_MANAGE,
    PERMISSIONS.DISCOUNT_VIEW,
    PERMISSIONS.DISCOUNT_CREATE,
    PERMISSIONS.DISCOUNT_EDIT,
    PERMISSIONS.DISCOUNT_DELETE,
    PERMISSIONS.APP_VERSION_VIEW,
    PERMISSIONS.APP_VERSION_MANAGE,
    PERMISSIONS.STATISTICS_VIEW,
    PERMISSIONS.NOTIFICATION_SEND,
  ],

  [AdminTier.MIDDLE]: [
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.MEMBER_MEMO,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_MANAGE,
    PERMISSIONS.CHAT_KEYWORD_BLOCK,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.COMMUNITY_CREATE,
    PERMISSIONS.COMMUNITY_EDIT,
    PERMISSIONS.FAQ_VIEW,
    PERMISSIONS.FAQ_CREATE,
    PERMISSIONS.FAQ_EDIT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_PROCESS,
    PERMISSIONS.SUBSCRIPTION_VIEW,
    PERMISSIONS.STATISTICS_VIEW,
  ],

  [AdminTier.GENERAL]: [
    PERMISSIONS.MEMBER_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.COMMUNITY_VIEW,
    PERMISSIONS.FAQ_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.SUBSCRIPTION_VIEW,
  ],
};

// Session Settings
export const SESSION = {
  ADMIN_TIMEOUT_MINUTES: 30, // 관리자 세션 타임아웃
  REMEMBER_ME_DAYS: 30,      // 자동 로그인 유지 기간
} as const;

// Pagination
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

// Chat Settings
export const CHAT = {
  MAX_PARTICIPANTS: 100,     // 최대 참여자 수
  MAX_MESSAGE_LENGTH: 1000,  // 최대 메시지 길이
  MAX_PINNED_MESSAGES: 10,   // 최대 고정 메시지 수
} as const;

// File Settings
export const FILE = {
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
  ALLOWED_DOCUMENT_TYPES: ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
  MAX_SIZE: 10 * 1024 * 1024, // 10MB
} as const;
